{
    "openapi": "3.0.1",
    "info": {
        "title": "OpenAPI definition",
        "version": "v0"
    },
    "servers": [
        {
            "url": "https://platform-api-a1jez.talroo.com/v5",
            "description": "Generated server url"
        }
    ],
    "tags": [
        {
            "name": "Locations - ZIP Codes"
        },
        {
            "name": "Locations - Cities"
        },
        {
            "name": "Enum - Pause Reasons"
        },
        {
            "name": "Locations - Counties"
        },
        {
            "name": "Job Campaigns"
        },
        {
            "name": "Scheduling - Monthly Budget Changes"
        },
        {
            "name": "Job Customers"
        },
        {
            "name": "App Clients"
        },
        {
            "name": "Locations - States"
        },
        {
            "name": "Job Segments"
        },
        {
            "name": "OAuth2"
        },
        {
            "name": "Enum - Categories"
        },
        {
            "name": "Job Pools"
        },
        {
            "name": "Scheduling - One Time Budgets"
        },
        {
            "name": "Jobs"
        },
        {
            "name": "Scheduling - Pauses"
        },
        {
            "name": "Companies"
        }
    ],
    "paths": {
        "/segments/{segmentId}/scheduling/pauses": {
            "get": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Get Platform Scheduled Pause by Segment ID",
                "operationId": "getScheduledPausesBySegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Create a Platform Scheduled Pause for a Segment",
                "operationId": "createScheduledPauseForSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/segments/{segmentId}/pause": {
            "post": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Set a JobSegment to Paused",
                "operationId": "pauseSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/segments/{segmentId}/launch": {
            "post": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Set a JobSegment to Live",
                "operationId": "launchSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/segments/{segmentId}/archive": {
            "post": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Archive a JobSegment",
                "operationId": "archiveSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/scheduling/monthly-budget-changes/{monthlyBudgetChangeId}/acknowledge": {
            "post": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Acknowledge a failed Monthly Budget Change",
                "operationId": "acknowledgeFailedMonthlyBudgetChange",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/pools/{poolId}/campaigns": {
            "get": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Get JobCampaigns by JobPool",
                "operationId": "getCampaignsByPool",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Create a JobCampaign",
                "operationId": "createCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/oauth2/token": {
            "post": {
                "tags": [
                    "OAuth2"
                ],
                "operationId": "oauth2Token",
                "security": [
                    {
                        "basic": []
                    }
                ]
            }
        },
        "/jobs/title-suggestions": {
            "post": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Get title suggestions for a Title And Description",
                "operationId": "createJobTitleSuggestions",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/app-clients": {
            "get": {
                "tags": [
                    "App Clients"
                ],
                "summary": "Get AppClients",
                "operationId": "getMyAppClients",
                "security": [
                    {
                        "bearer": [
                            "integration"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "App Clients"
                ],
                "summary": "Create an AppClient",
                "operationId": "createAppClient",
                "security": [
                    {
                        "bearer": [
                            "integration"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/segments": {
            "get": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Get a JobCampaign's JobSegments",
                "operationId": "getSegmentsByCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Create a JobSegment",
                "operationId": "createSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/scheduling/pauses": {
            "get": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Get Platform Scheduled Pause by Campaign ID",
                "operationId": "getScheduledPausesByCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Create a Platform Scheduled Pause",
                "operationId": "createScheduledPauseForCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/scheduling/one-time-budgets": {
            "get": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Get OneTimeBudgets by Campaign",
                "operationId": "getOneTimeBudgetsByCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Create a OneTimeBudget",
                "description": "**NOTE:** By default, non-LIVE Campaigns will be launched when the OneTimeBudget is started. To change this behavior, set the `launchOnStart` property in the request body to `false`.",
                "operationId": "createOneTimeBudget",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/scheduling/monthly-budget-changes": {
            "get": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Get Monthly Budget Changes",
                "operationId": "getMonthlyBudgetChangesByCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Create a Monthly Budget Change for a Campaign",
                "operationId": "createMonthlyBudgetChange",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/pause": {
            "post": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Set a JobCampaign to Paused",
                "operationId": "pauseCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/launch": {
            "post": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Set a JobCampaign to Live",
                "operationId": "launchCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}/archive": {
            "post": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Archive a JobCampaign",
                "operationId": "archiveCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/segments/{segmentId}": {
            "get": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Get a JobSegment by ID",
                "operationId": "getSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Update a JobSegment",
                "operationId": "updateSegment",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/scheduling/pauses/{pauseId}": {
            "get": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Get a Scheduled Pause by ID",
                "operationId": "getScheduledPause",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Delete a Scheduled Pause",
                "operationId": "deleteScheduledPause",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Update a Platform Scheduled Pause",
                "operationId": "updateScheduledPause",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/scheduling/one-time-budgets/{oneTimeBudgetId}": {
            "get": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Get a OneTimeBudget by ID",
                "operationId": "getOneTimeBudget",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Delete a OneTimeBudget",
                "operationId": "deleteOneTimeBudget",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Update a OneTimeBudget",
                "description": "**NOTE:** By default, non-LIVE Campaigns will be launched when the OneTimeBudget is started. To change this behavior, set the `launchOnStart` property in the request body to `false`.",
                "operationId": "updateOneTimeBudget",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/scheduling/monthly-budget-changes/{monthlyBudgetChangeId}": {
            "get": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Get a Monthly Budget Change by ID",
                "operationId": "getMonthlyBudgetChange",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Delete a Monthly Budget Change",
                "operationId": "deleteMonthlyBudgetChange",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Update a Monthly Budget Change",
                "operationId": "updateMonthlyBudgetChange",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/campaigns/{campaignId}": {
            "get": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Get a JobCampaign by ID",
                "operationId": "getCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Update a JobCampaign",
                "operationId": "updateCampaign",
                "security": [
                    {
                        "bearer": [
                            "advertiser"
                        ]
                    }
                ]
            }
        },
        "/pools/{poolId}": {
            "get": {
                "tags": [
                    "Job Pools"
                ],
                "summary": "Get a JobPool by ID",
                "operationId": "getPool",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/pause-reasons": {
            "get": {
                "tags": [
                    "Enum - Pause Reasons"
                ],
                "summary": "Get Pause Reasons",
                "operationId": "getPauseReasons",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/pause-reasons/{pauseReasonId}": {
            "get": {
                "tags": [
                    "Enum - Pause Reasons"
                ],
                "summary": "Get a Pause Reason by ID",
                "operationId": "getPauseReason",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/zipcodes": {
            "get": {
                "tags": [
                    "Locations - ZIP Codes"
                ],
                "summary": "Get US ZipCodes",
                "operationId": "getZipcodes",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/zipcodes/{zipCode}": {
            "get": {
                "tags": [
                    "Locations - ZIP Codes"
                ],
                "summary": "Get a US ZipCode By ZipCode",
                "operationId": "getZipcode",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/states": {
            "get": {
                "tags": [
                    "Locations - States"
                ],
                "summary": "Get States",
                "operationId": "getStates",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/states/{stateId}": {
            "get": {
                "tags": [
                    "Locations - States"
                ],
                "summary": "Get a State by ID",
                "operationId": "getState",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/states/{stateId}/zipcodes": {
            "get": {
                "tags": [
                    "Locations - ZIP Codes"
                ],
                "summary": "Get US ZipCodes by US State",
                "operationId": "getZipcodesByState",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/states/{stateId}/counties": {
            "get": {
                "tags": [
                    "Locations - Counties"
                ],
                "summary": "Get US Counties by US State",
                "operationId": "getCountiesByState",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/states/{stateId}/cities": {
            "get": {
                "tags": [
                    "Locations - Cities"
                ],
                "summary": "Get US Cities By US State",
                "operationId": "getCitiesByState",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/counties": {
            "get": {
                "tags": [
                    "Locations - Counties"
                ],
                "summary": "Get US Counties",
                "operationId": "getCounties",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/counties/{countyId}": {
            "get": {
                "tags": [
                    "Locations - Counties"
                ],
                "summary": "Get a US County by ID",
                "operationId": "getCounty",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/counties/{countyId}/cities": {
            "get": {
                "tags": [
                    "Locations - Cities"
                ],
                "summary": "Get US Cities By US County",
                "operationId": "getCitiesByCounty",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/cities": {
            "get": {
                "tags": [
                    "Locations - Cities"
                ],
                "summary": "Get US Cities",
                "operationId": "getCities",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/cities/{cityId}": {
            "get": {
                "tags": [
                    "Locations - Cities"
                ],
                "summary": "Get a US City by ID",
                "operationId": "getCity",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/locations/us/cities/{cityId}/zipcodes": {
            "get": {
                "tags": [
                    "Locations - ZIP Codes"
                ],
                "summary": "Get US ZipCodes by US City",
                "operationId": "getZipcodesByCity",
                "security": [
                    {
                        "bearer": [
                            "location:read"
                        ]
                    }
                ]
            }
        },
        "/jobs/{id}": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Get a Job by ID",
                "operationId": "getJob",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/jobs/{id}/title-suggestions": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Get title suggestions for a Job",
                "operationId": "getJobTitleSuggestions",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/jobs/{id}/shareable-links": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Get shareable links to the Job",
                "operationId": "getJobShareableLinks",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me": {
            "get": {
                "tags": [
                    "Job Customers"
                ],
                "summary": "Get my Customer",
                "operationId": "getMyCustomer",
                "security": [
                    {
                        "bearer": [
                            "customer:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/segments": {
            "get": {
                "tags": [
                    "Job Segments"
                ],
                "summary": "Get my JobSegments",
                "operationId": "getMySegments",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/scheduling/pauses": {
            "get": {
                "tags": [
                    "Scheduling - Pauses"
                ],
                "summary": "Get my Scheduled Pauses",
                "operationId": "getMyScheduledPauses",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/scheduling/one-time-budgets": {
            "get": {
                "tags": [
                    "Scheduling - One Time Budgets"
                ],
                "summary": "Get my OneTimeBudgets",
                "operationId": "getMyOneTimeBudgets",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/scheduling/monthly-budget-changes": {
            "get": {
                "tags": [
                    "Scheduling - Monthly Budget Changes"
                ],
                "summary": "Get Monthly Budget Changes",
                "operationId": "getMyMonthlyBudgetChanges",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/pools": {
            "get": {
                "tags": [
                    "Job Pools"
                ],
                "summary": "Get my JobPools",
                "operationId": "getMyPools",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/jobs": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Search my Jobs",
                "description": "Available Sort Fields: campaignName, campaign, cities, location, company, jobReference, majorCategory, majorCategoryName, minorCategory, minorCategoryName, segmentName, segment, states, title, zipcodes",
                "operationId": "getMyJobs",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/jobs/facet/{facetField}": {
            "get": {
                "tags": [
                    "Jobs"
                ],
                "summary": "Drill down on my Jobs",
                "operationId": "getMyJobFacets",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/companies": {
            "get": {
                "tags": [
                    "Companies"
                ],
                "summary": "Get my Companies",
                "operationId": "getMyCompanies",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/customers/me/campaigns": {
            "get": {
                "tags": [
                    "Job Campaigns"
                ],
                "summary": "Get my JobCampaigns",
                "operationId": "getMyCampaigns",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/companies": {
            "get": {
                "tags": [
                    "Companies"
                ],
                "summary": "Get Companies",
                "operationId": "getCompanies",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/companies/{companyId}": {
            "get": {
                "tags": [
                    "Companies"
                ],
                "summary": "Get a Company by ID",
                "operationId": "getCompany",
                "security": [
                    {
                        "bearer": [
                            "advertiser:read"
                        ]
                    }
                ]
            }
        },
        "/categories": {
            "get": {
                "tags": [
                    "Enum - Categories"
                ],
                "summary": "Get Categories",
                "operationId": "getCategories",
                "security": [
                    {
                        "bearer": [
                            "category:read"
                        ]
                    }
                ]
            }
        },
        "/categories/{categoryId}": {
            "get": {
                "tags": [
                    "Enum - Categories"
                ],
                "summary": "Get a Category by ID",
                "operationId": "getCategory",
                "security": [
                    {
                        "bearer": [
                            "category:read"
                        ]
                    }
                ]
            }
        },
        "/app-clients/{id}": {
            "get": {
                "tags": [
                    "App Clients"
                ],
                "summary": "Get an AppClient by ID",
                "operationId": "getAppClient",
                "security": [
                    {
                        "bearer": [
                            "integration"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "App Clients"
                ],
                "summary": "Delete an AppClient by ID",
                "operationId": "deleteAppClient",
                "security": [
                    {
                        "bearer": [
                            "integration"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            },
            "basic": {
                "type": "http",
                "scheme": "basic"
            }
        }
    }
}
